server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://192.168.64.6:3306/dev
      username: sdai002
      password: cloud1234
      pool-name: CP
      maximum-pool-size: 20
      connection-timeout: 8000
      max-lifetime: 298000